<?php

namespace Database\Seeders;

use App\Models\Module;
use App\Models\SubModule;
use Illuminate\Database\Seeder;

class ModuleSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->modules() as $sort => $data) {
            $subModules = $data['sub_modules'] ?? [];
            unset($data['sub_modules']);

            $data['sort_order'] = $sort + 1;

            $module = Module::updateOrCreate(['key' => $data['key']], $data);

            foreach ($subModules as $subSort => $sub) {
                $sub['module_id']   = $module->id;
                $sub['sort_order']  = $subSort + 1;

                SubModule::updateOrCreate(['key' => $sub['key']], $sub);
            }
        }
    }

    private function modules(): array
    {
        return [
            // ──────────────────────────────────────────────────────────
            // DOMAIN 0 — Core Platform (always active)
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'authentication-identity',
                'name'        => 'Authentication & Identity',
                'description' => 'Multi-method login, session management, 2FA, and admin impersonation.',
                'domain'      => 'core',
                'panel_id'    => null,
                'icon'        => 'heroicon-o-finger-print',
                'color'       => '#6366F1',
                'is_core'     => true,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'auth-login-methods',      'name' => 'Login Methods',                   'description' => 'Email/password, Google OAuth, Microsoft OAuth, GitHub OAuth, SAML SSO, magic link, passkey.'],
                    ['key' => 'auth-two-factor',         'name' => 'Two-Factor Authentication',        'description' => 'TOTP authenticator app, SMS OTP, backup recovery codes, workspace-enforced 2FA.'],
                    ['key' => 'auth-session-management', 'name' => 'Session Management',               'description' => 'Active session list, remote revoke, session timeout config, concurrent session limits.'],
                    ['key' => 'auth-impersonation',      'name' => 'Admin Impersonation',              'description' => 'Super-admin and workspace-admin impersonation with audit log and visible banner.'],
                ],
            ],
            [
                'key'         => 'rbac',
                'name'        => 'Roles & Permissions',
                'description' => 'Granular RBAC built on Spatie Laravel Permission. Panel, resource, and field-level access control.',
                'domain'      => 'core',
                'panel_id'    => null,
                'icon'        => 'heroicon-o-shield-check',
                'color'       => '#6366F1',
                'is_core'     => true,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'rbac-role-builder',          'name' => 'Role Builder',           'description' => 'Create custom roles, role inheritance, clone, bulk assign.'],
                    ['key' => 'rbac-permission-layers',     'name' => 'Permission Layers',      'description' => 'Panel-level, resource-level, and field-level permissions. Permission matrix UI.'],
                    ['key' => 'rbac-scoping-restrictions',  'name' => 'Scoping & Restrictions', 'description' => 'Department, team, and location scoping. IP allowlist, time-based windows, temporary grants.'],
                ],
            ],
            [
                'key'         => 'module-billing',
                'name'        => 'Module Billing Engine',
                'description' => 'Tracks which modules are active per tenant, meters usage, and bills via Stripe.',
                'domain'      => 'core',
                'panel_id'    => 'workspace',
                'icon'        => 'heroicon-o-credit-card',
                'color'       => '#6366F1',
                'is_core'     => true,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'billing-module-toggle',   'name' => 'Module Toggle',    'description' => 'Module marketplace, toggle on/off, dependency warnings, preview mode, activation wizard.'],
                    ['key' => 'billing-plan-management', 'name' => 'Plan Management',  'description' => 'Starter/Pro/Enterprise tiers, Stripe Billing, annual discount, seat and module pricing, overages.'],
                    ['key' => 'billing-usage-metering',  'name' => 'Usage Metering',   'description' => 'Event-based metering, usage dashboard, billing period summary, limit alerts, historical graphs.'],
                    ['key' => 'billing-trial-management','name' => 'Trial Management', 'description' => '14-day free trial, trial countdown banner, conversion flow, sales team notification.'],
                ],
            ],
            [
                'key'         => 'notifications',
                'name'        => 'Notifications & Alerts',
                'description' => 'Central notification hub. Every module dispatches notifications here. Users control channels and preferences.',
                'domain'      => 'core',
                'panel_id'    => null,
                'icon'        => 'heroicon-o-bell',
                'color'       => '#6366F1',
                'is_core'     => true,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'notif-channels',   'name' => 'Notification Channels', 'description' => 'In-app bell, email, Slack, Teams, SMS (Twilio), browser push, webhook dispatch.'],
                    ['key' => 'notif-preferences','name' => 'User Preferences',      'description' => 'Per-user preferences per notification type, digest options, quiet hours, channel priority, mute per record.'],
                    ['key' => 'notif-escalation', 'name' => 'Escalation Rules',      'description' => 'Escalation chains, priority levels, bypass quiet hours for critical, workspace-level defaults.'],
                ],
            ],
            [
                'key'         => 'api-integrations',
                'name'        => 'API & Integrations Layer',
                'description' => 'Every active module exposes its data through this layer. REST API, webhooks, API keys, and native connectors.',
                'domain'      => 'core',
                'panel_id'    => 'workspace',
                'icon'        => 'heroicon-o-code-bracket',
                'color'       => '#6366F1',
                'is_core'     => true,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'api-rest',              'name' => 'REST API',            'description' => 'Versioned REST API (/api/v1/), per active module, OpenAPI docs, Postman export.'],
                    ['key' => 'api-key-management',    'name' => 'API Key Management',  'description' => 'Named scoped keys, expiry dates, last used tracking, instant revoke, rotation reminders.'],
                    ['key' => 'api-webhooks',          'name' => 'Webhooks',            'description' => 'Outbound event webhooks, HMAC-SHA256 signing, delivery log, retry, inbound URLs.'],
                    ['key' => 'api-native-connectors', 'name' => 'Native Connectors',   'description' => 'Google Workspace, Microsoft 365, QuickBooks, Xero, Shopify, WooCommerce, Stripe, Twilio, Zapier, Make.'],
                ],
            ],
            [
                'key'         => 'multi-tenancy',
                'name'        => 'Multi-Tenancy & Workspace',
                'description' => 'Manages the complete isolation and configuration of each tenant workspace. Branding, locale, backup, and subdomain.',
                'domain'      => 'core',
                'panel_id'    => 'workspace',
                'icon'        => 'heroicon-o-building-office',
                'color'       => '#6366F1',
                'is_core'     => true,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'tenancy-workspace-setup',  'name' => 'Workspace Setup',          'description' => 'Creation wizard, subdomain, custom domain (CNAME), avatar, owner designation, initial module selection.'],
                    ['key' => 'tenancy-branding',         'name' => 'Branding & White-label',   'description' => 'Logo, brand colour, email sender, client portal white-label, custom login background.'],
                    ['key' => 'tenancy-locale',           'name' => 'Locale & Regionalisation', 'description' => 'Timezone, date format, primary currency, language, number format, first day of week.'],
                    ['key' => 'tenancy-backup',           'name' => 'Backup & Data Management', 'description' => 'Scheduled exports, on-demand full export, data retention policies, GDPR erasure.'],
                ],
            ],

            // ──────────────────────────────────────────────────────────
            // DOMAIN 1 — HR & People Management
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'hr-employee-profiles',
                'name'        => 'Employee Profiles & Directory',
                'description' => 'Central record for every person. All other HR modules reference this.',
                'domain'      => 'hr',
                'panel_id'    => 'hr',
                'icon'        => 'heroicon-o-identification',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'hr-onboarding',
                'name'        => 'Onboarding',
                'description' => 'Structured, templated journeys for every new hire from pre-boarding to 90-day check-ins.',
                'domain'      => 'hr',
                'panel_id'    => 'hr',
                'icon'        => 'heroicon-o-user-plus',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'onboarding-preboarding',  'name' => 'Pre-boarding Portal',         'description' => 'Branded portal for new hires before day 1. Document collection, contract e-sign, personal details form.'],
                    ['key' => 'onboarding-templates',    'name' => 'Onboarding Templates',        'description' => 'Template builder by role/department, task types, default assignees, relative due dates.'],
                    ['key' => 'onboarding-tasks',        'name' => 'Onboarding Task Management',  'description' => 'HR, new hire, and manager task checklists. Progress bar, overdue alerts, completion notifications.'],
                    ['key' => 'onboarding-checkins',     'name' => '30/60/90-Day Check-ins',      'description' => 'Automated check-in forms for new hires and managers at 30, 60, and 90 days.'],
                ],
            ],
            [
                'key'         => 'hr-offboarding',
                'name'        => 'Offboarding',
                'description' => 'Controlled exit process — exit interview, knowledge handover, asset return, access revocation, final payroll.',
                'domain'      => 'hr',
                'panel_id'    => 'hr',
                'icon'        => 'heroicon-o-user-minus',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'hr-leave-management',
                'name'        => 'Leave & Absence Management',
                'description' => 'End-to-end leave request, approval, balance tracking, and policy management.',
                'domain'      => 'hr',
                'panel_id'    => 'hr',
                'icon'        => 'heroicon-o-calendar-days',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'leave-types-policies', 'name' => 'Leave Types & Policies',    'description' => 'Leave type config, accrual rules, carry-over, caps, blackout periods, multi-country law presets.'],
                    ['key' => 'leave-requests',       'name' => 'Leave Requests & Approval', 'description' => 'Employee submission, manager approval, multi-level, overlap check, cancellation flow.'],
                    ['key' => 'leave-balances',       'name' => 'Leave Balances & Calendar', 'description' => 'Self-service balance view, manager team calendar, public holiday calendar, year-end reporting.'],
                ],
            ],
            [
                'key'         => 'hr-payroll',
                'name'        => 'Payroll',
                'description' => 'Full payroll calculation and processing. Pulls from Time Tracking, Leave, and Expenses automatically.',
                'domain'      => 'hr',
                'panel_id'    => 'hr',
                'icon'        => 'heroicon-o-banknotes',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'payroll-configuration',   'name' => 'Payroll Configuration',          'description' => 'Pay frequency, pay elements, tax year settings, pension/NI, multiple payroll entities.'],
                    ['key' => 'payroll-pay-run',         'name' => 'Pay Run Processing',             'description' => 'Auto-pull time/expenses/leave, manual adjustments, tax calc, BACS/ACH/SEPA export.'],
                    ['key' => 'payroll-payslips',        'name' => 'Payslips & Reporting',           'description' => 'PDF payslip generation, email to employee, self-service history, RTI/FPS, P60/P45.'],
                    ['key' => 'payroll-contractors',     'name' => 'Contractor & Hourly Payroll',    'description' => 'Contractor payment runs, hourly worker support, IR35 flag, self-billing invoices.'],
                ],
            ],
            [
                'key'         => 'hr-performance-reviews',
                'name'        => 'Performance & Reviews',
                'description' => 'OKRs, review cycles, 360 feedback, calibration, and development planning.',
                'domain'      => 'hr',
                'panel_id'    => 'hr',
                'icon'        => 'heroicon-o-chart-bar',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'hr-recruitment',
                'name'        => 'Recruitment & ATS',
                'description' => 'Full applicant tracking system from job requisition to signed offer letter, with automatic hand-off to onboarding.',
                'domain'      => 'hr',
                'panel_id'    => 'hr',
                'icon'        => 'heroicon-o-briefcase',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'recruitment-job-requisitions', 'name' => 'Job Requisitions & Postings', 'description' => 'Requisition form, headcount approval, job builder, careers page embed, multi-channel publishing.'],
                    ['key' => 'recruitment-pipeline',        'name' => 'Application Pipeline',        'description' => 'Kanban pipeline per job, bulk actions, source tracking, CV parsing, candidate profiles.'],
                    ['key' => 'recruitment-interviews',      'name' => 'Interviews & Scorecards',      'description' => 'Interview scheduling, scorecard builder, panel coordination, feedback compilation.'],
                    ['key' => 'recruitment-offers',          'name' => 'Offers & Closing',             'description' => 'Offer letter generator, approval workflow, e-signature, offer status tracking.'],
                    ['key' => 'recruitment-referrals',       'name' => 'Referral Programme',           'description' => 'Employee referral submission, referral tracking, bonus config, automated payout trigger.'],
                ],
            ],
            [
                'key'         => 'hr-scheduling',
                'name'        => 'Scheduling & Shifts',
                'description' => 'Shift planning for hourly workers with drag-and-drop rota builder, clock-in/out, and payroll integration.',
                'domain'      => 'hr',
                'panel_id'    => 'hr',
                'icon'        => 'heroicon-o-clock',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'hr-benefits',
                'name'        => 'Benefits & Perks',
                'description' => 'Benefits catalogue with eligibility rules. Employee enrolment portal. Costs sync to payroll deductions.',
                'domain'      => 'hr',
                'panel_id'    => 'hr',
                'icon'        => 'heroicon-o-gift',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'hr-feedback-engagement',
                'name'        => 'Employee Feedback & Engagement',
                'description' => 'Pulse surveys, eNPS tracking, burnout signal detection, anonymous feedback, and recognition system.',
                'domain'      => 'hr',
                'panel_id'    => 'hr',
                'icon'        => 'heroicon-o-heart',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'hr-compliance',
                'name'        => 'HR Compliance & Certifications',
                'description' => 'Mandatory training tracking, certification expiry alerts, policy acknowledgements, and right-to-work checks.',
                'domain'      => 'hr',
                'panel_id'    => 'hr',
                'icon'        => 'heroicon-o-shield-exclamation',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],

            // ──────────────────────────────────────────────────────────
            // DOMAIN 2 — Projects & Work Management
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'projects-task-management',
                'name'        => 'Task Management',
                'description' => 'Kanban, list, calendar, timeline, and My Work views. Subtasks, dependencies, automations, and recurring tasks.',
                'domain'      => 'projects',
                'panel_id'    => 'projects',
                'icon'        => 'heroicon-o-check-circle',
                'color'       => '#4F46E5',
                'is_core'     => false,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'tasks-views',      'name' => 'Task Views',       'description' => 'Kanban, list, calendar, timeline, My Work, grouping options.'],
                    ['key' => 'tasks-properties', 'name' => 'Task Properties',  'description' => 'Assignee, due date, priority, subtasks, dependencies, attachments, time log, linked records.'],
                    ['key' => 'tasks-automations','name' => 'Task Automations', 'description' => 'Trigger/action rules: status change, due date, assignee. Automation log, enable/disable per project.'],
                    ['key' => 'tasks-recurring',  'name' => 'Recurring Tasks',  'description' => 'Daily/weekly/monthly/custom recurrence, end conditions, new instance on completion.'],
                ],
            ],
            [
                'key'         => 'projects-project-planning',
                'name'        => 'Project Planning',
                'description' => 'Gantt chart, milestones, dependencies, critical path, baseline vs actual, portfolio view.',
                'domain'      => 'projects',
                'panel_id'    => 'projects',
                'icon'        => 'heroicon-o-chart-bar-square',
                'color'       => '#4F46E5',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'projects-time-tracking',
                'name'        => 'Time Tracking',
                'description' => 'One-click timer or manual entry. Tag to project, client, task. Timesheet submission and approval. Feeds payroll and client billing.',
                'domain'      => 'projects',
                'panel_id'    => 'projects',
                'icon'        => 'heroicon-o-clock',
                'color'       => '#4F46E5',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'projects-document-management',
                'name'        => 'Document Management',
                'description' => 'Centralised file storage with versioning, permissions, full-text search, preview, and cloud sync.',
                'domain'      => 'projects',
                'panel_id'    => 'projects',
                'icon'        => 'heroicon-o-folder',
                'color'       => '#4F46E5',
                'is_core'     => false,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'docs-file-storage',   'name' => 'File Storage & Organisation', 'description' => 'Nested folder structure, drag-and-drop upload, tagging, metadata, duplicate detection.'],
                    ['key' => 'docs-version-history', 'name' => 'Version History',            'description' => 'Every upload creates a version, restore previous, compare versions, retention policy.'],
                    ['key' => 'docs-permissions',     'name' => 'File Permissions',           'description' => 'Folder/file permissions per user or role, public sharing links, external email invite.'],
                    ['key' => 'docs-search-preview',  'name' => 'Search & Preview',           'description' => 'Full-text search, OCR on scanned PDFs, in-browser preview, recent/starred files.'],
                    ['key' => 'docs-cloud-sync',      'name' => 'Cloud Sync',                 'description' => 'Google Drive and Microsoft OneDrive two-way sync, conflict resolution.'],
                ],
            ],
            [
                'key'         => 'projects-document-approvals',
                'name'        => 'Document Approvals & E-Sign',
                'description' => 'Formal approval workflows with sequential/parallel chains, e-signature, rejection flow, and full audit trail.',
                'domain'      => 'projects',
                'panel_id'    => 'projects',
                'icon'        => 'heroicon-o-pencil-square',
                'color'       => '#4F46E5',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'projects-knowledge-base',
                'name'        => 'Knowledge Base & Wiki',
                'description' => 'Rich block editor, nested pages, versioning, article templates, full-text search, public/private articles.',
                'domain'      => 'projects',
                'panel_id'    => 'projects',
                'icon'        => 'heroicon-o-book-open',
                'color'       => '#4F46E5',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'projects-team-collaboration',
                'name'        => 'Team Collaboration',
                'description' => 'Comment threads, @mentions, activity feed, project announcements, and watching on any record.',
                'domain'      => 'projects',
                'panel_id'    => 'projects',
                'icon'        => 'heroicon-o-chat-bubble-left-right',
                'color'       => '#4F46E5',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'projects-resource-capacity',
                'name'        => 'Resource & Capacity Planning',
                'description' => 'Workload heatmap, individual and team capacity, role-based demand, leave overlay, rebalancing suggestions.',
                'domain'      => 'projects',
                'panel_id'    => 'projects',
                'icon'        => 'heroicon-o-users',
                'color'       => '#4F46E5',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'projects-agile-sprint',
                'name'        => 'Agile & Sprint Management',
                'description' => 'Backlog, sprint planning, story points, burndown chart, velocity tracking, retrospectives, release management.',
                'domain'      => 'projects',
                'panel_id'    => 'projects',
                'icon'        => 'heroicon-o-arrow-path',
                'color'       => '#4F46E5',
                'is_core'     => false,
                'is_available'=> true,
            ],

            // ──────────────────────────────────────────────────────────
            // DOMAIN 3 — Finance & Accounting
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'finance-invoicing',
                'name'        => 'Invoicing',
                'description' => 'Invoice builder, auto-generate from time or milestones, recurring, multi-currency, PDF, payment tracking.',
                'domain'      => 'finance',
                'panel_id'    => 'finance',
                'icon'        => 'heroicon-o-document-text',
                'color'       => '#059669',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'finance-expense-management',
                'name'        => 'Expense Management',
                'description' => 'Receipt upload with OCR, mileage tracking, per diem, approval workflow, reimbursement via payroll.',
                'domain'      => 'finance',
                'panel_id'    => 'finance',
                'icon'        => 'heroicon-o-receipt-percent',
                'color'       => '#059669',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'finance-accounts-payable-receivable',
                'name'        => 'Accounts Payable & Receivable',
                'description' => 'Supplier bill management, payment runs, 3-way matching (PO/receipt/invoice), aged debtor/creditor reports.',
                'domain'      => 'finance',
                'panel_id'    => 'finance',
                'icon'        => 'heroicon-o-arrows-right-left',
                'color'       => '#059669',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'finance-bank-reconciliation',
                'name'        => 'Bank Reconciliation',
                'description' => 'Open Banking connection, auto-matching rules, unmatched transaction queue, multi-account, monthly sign-off.',
                'domain'      => 'finance',
                'panel_id'    => 'finance',
                'icon'        => 'heroicon-o-building-library',
                'color'       => '#059669',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'finance-budgeting-forecasting',
                'name'        => 'Budgeting & Forecasting',
                'description' => 'Department and project budgets, actuals pull-through, variance tracking, over-budget alerts, scenario planning.',
                'domain'      => 'finance',
                'panel_id'    => 'finance',
                'icon'        => 'heroicon-o-presentation-chart-line',
                'color'       => '#059669',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'finance-financial-reporting',
                'name'        => 'Financial Reporting',
                'description' => 'P&L, balance sheet, cash flow, custom report builder, scheduled delivery, consolidation, department P&L.',
                'domain'      => 'finance',
                'panel_id'    => 'finance',
                'icon'        => 'heroicon-o-chart-pie',
                'color'       => '#059669',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'finance-client-billing',
                'name'        => 'Client Billing & Retainers',
                'description' => 'Time-to-invoice conversion, retainer management, client payment portal, unbilled time alerts.',
                'domain'      => 'finance',
                'panel_id'    => 'finance',
                'icon'        => 'heroicon-o-user-group',
                'color'       => '#059669',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'finance-tax-vat',
                'name'        => 'Tax & VAT Compliance',
                'description' => 'Tax code config, VAT return preparation, MTD (UK), US sales tax nexus, reverse charge, tax liability report.',
                'domain'      => 'finance',
                'panel_id'    => 'finance',
                'icon'        => 'heroicon-o-scale',
                'color'       => '#059669',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'finance-fixed-assets',
                'name'        => 'Fixed Asset & Depreciation',
                'description' => 'Asset register (financial view), multiple depreciation methods, NBV reporting, disposal, capex tracking.',
                'domain'      => 'finance',
                'panel_id'    => 'finance',
                'icon'        => 'heroicon-o-cube',
                'color'       => '#059669',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'finance-mrr-tracking',
                'name'        => 'Subscription & MRR Tracking',
                'description' => 'MRR/ARR dashboard, churn tracking, cohort analysis, LTV, revenue recognition (ASC 606/IFRS 15).',
                'domain'      => 'finance',
                'panel_id'    => 'finance',
                'icon'        => 'heroicon-o-arrow-trending-up',
                'color'       => '#059669',
                'is_core'     => false,
                'is_available'=> true,
            ],

            // ──────────────────────────────────────────────────────────
            // DOMAIN 4 — CRM & Sales
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'crm-contacts',
                'name'        => 'Contact & Company Management',
                'description' => '360° contact and company records with activity timeline, custom fields, data enrichment, duplicate detection.',
                'domain'      => 'crm',
                'panel_id'    => 'crm',
                'icon'        => 'heroicon-o-identification',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'crm-sales-pipeline',
                'name'        => 'Sales Pipeline',
                'description' => 'Visual deal pipeline, custom stages, probability weighting, revenue forecasting, win/loss tracking.',
                'domain'      => 'crm',
                'panel_id'    => 'crm',
                'icon'        => 'heroicon-o-funnel',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'crm-quotes-proposals',
                'name'        => 'Quotes & Proposals',
                'description' => 'Quote builder from product catalogue, discount rules, convert to invoice, view tracking, e-signature on acceptance.',
                'domain'      => 'crm',
                'panel_id'    => 'crm',
                'icon'        => 'heroicon-o-document-duplicate',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'crm-shared-inbox',
                'name'        => 'Shared Inbox & Email',
                'description' => 'Shared team inbox, email sequences, templates, open/click tracking, auto-log to contact timeline.',
                'domain'      => 'crm',
                'panel_id'    => 'crm',
                'icon'        => 'heroicon-o-inbox',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'crm-customer-data-platform',
                'name'        => 'Customer Data Platform',
                'description' => 'Unified customer profile across modules, dynamic segmentation, behaviour tracking, identity resolution.',
                'domain'      => 'crm',
                'panel_id'    => 'crm',
                'icon'        => 'heroicon-o-circle-stack',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'crm-customer-support',
                'name'        => 'Customer Support & Helpdesk',
                'description' => 'Ticket management, SLA rules, escalation, canned responses, CSAT surveys, live chat, chatbot, self-service portal.',
                'domain'      => 'crm',
                'panel_id'    => 'crm',
                'icon'        => 'heroicon-o-lifebuoy',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'support-tickets',      'name' => 'Ticket Management',      'description' => 'Multi-channel ticket management (email, form, chat), status workflow, assignment rules.'],
                    ['key' => 'support-sla',          'name' => 'SLA Rules',              'description' => 'Response and resolution SLA targets, escalation paths, breach notifications.'],
                    ['key' => 'support-canned',       'name' => 'Canned Responses',       'description' => 'Response library, quick insert, personalisation tokens.'],
                    ['key' => 'support-live-chat',    'name' => 'Live Chat Widget',       'description' => 'Embeddable chat widget, real-time conversation, file sharing.'],
                    ['key' => 'support-chatbot',      'name' => 'Rule-based Chatbot',     'description' => 'Automated first-line response, FAQ deflection, handoff to human agent.'],
                    ['key' => 'support-self-service', 'name' => 'Self-service Portal',    'description' => 'Customer portal for ticket submission, status tracking, knowledge base access.'],
                ],
            ],
            [
                'key'         => 'crm-client-portal',
                'name'        => 'Client Portal',
                'description' => 'Branded self-service portal for clients. Project status, invoice payment, document sharing, support ticket raising.',
                'domain'      => 'crm',
                'panel_id'    => 'crm',
                'icon'        => 'heroicon-o-globe-alt',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'crm-loyalty-retention',
                'name'        => 'Loyalty & Retention',
                'description' => 'Points and rewards programme, referral tracking, churn prediction score, win-back campaign triggers.',
                'domain'      => 'crm',
                'panel_id'    => 'crm',
                'icon'        => 'heroicon-o-star',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],

            // ──────────────────────────────────────────────────────────
            // DOMAIN 5 — Marketing & Content
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'marketing-cms',
                'name'        => 'CMS & Website Builder',
                'description' => 'Block-based page builder, blog, SEO meta fields, media library, multi-language, A/B test pages, headless CMS API.',
                'domain'      => 'marketing',
                'panel_id'    => 'marketing',
                'icon'        => 'heroicon-o-globe-alt',
                'color'       => '#D97706',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'marketing-email',
                'name'        => 'Email Marketing',
                'description' => 'Campaign builder, drag-and-drop editor, automation flows, A/B testing, deliverability tools.',
                'domain'      => 'marketing',
                'panel_id'    => 'marketing',
                'icon'        => 'heroicon-o-envelope',
                'color'       => '#D97706',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'marketing-social-media',
                'name'        => 'Social Media Management',
                'description' => 'Content calendar, multi-channel publishing, approval workflow, best-time suggestions, performance analytics.',
                'domain'      => 'marketing',
                'panel_id'    => 'marketing',
                'icon'        => 'heroicon-o-share',
                'color'       => '#D97706',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'marketing-forms',
                'name'        => 'Forms & Lead Capture',
                'description' => 'Drag-and-drop form builder, conditional logic, file upload, iframe/JS embed, auto-create CRM contact on submit.',
                'domain'      => 'marketing',
                'panel_id'    => 'marketing',
                'icon'        => 'heroicon-o-clipboard-document-list',
                'color'       => '#D97706',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'marketing-seo',
                'name'        => 'SEO & Analytics',
                'description' => 'Keyword rank tracking, technical SEO audit, backlink monitoring, Google Search Console and GA4 integration.',
                'domain'      => 'marketing',
                'panel_id'    => 'marketing',
                'icon'        => 'heroicon-o-magnifying-glass',
                'color'       => '#D97706',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'marketing-ad-campaigns',
                'name'        => 'Ad Campaign Management',
                'description' => 'Google Ads and Meta Ads connection, spend tracking, ROAS dashboard, conversion attribution.',
                'domain'      => 'marketing',
                'panel_id'    => 'marketing',
                'icon'        => 'heroicon-o-megaphone',
                'color'       => '#D97706',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'marketing-events-webinars',
                'name'        => 'Events & Webinars',
                'description' => 'Event registration pages, attendee management, QR code check-in, post-event follow-up automation.',
                'domain'      => 'marketing',
                'panel_id'    => 'marketing',
                'icon'        => 'heroicon-o-ticket',
                'color'       => '#D97706',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'marketing-affiliate',
                'name'        => 'Affiliate & Partner Management',
                'description' => 'Affiliate portal, referral link generation, commission rules, payout management, performance reports.',
                'domain'      => 'marketing',
                'panel_id'    => 'marketing',
                'icon'        => 'heroicon-o-link',
                'color'       => '#D97706',
                'is_core'     => false,
                'is_available'=> true,
            ],

            // ──────────────────────────────────────────────────────────
            // DOMAIN 6 — Operations & Field Service
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'operations-inventory',
                'name'        => 'Inventory Management',
                'description' => 'Real-time stock levels, multi-location warehouses, barcode scanning, batch/serial tracking, stocktake workflows.',
                'domain'      => 'operations',
                'panel_id'    => 'operations',
                'icon'        => 'heroicon-o-archive-box',
                'color'       => '#EA580C',
                'is_core'     => false,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'inventory-stock-levels',   'name' => 'Real-time Stock Levels',    'description' => 'Live stock counts, reorder point alerts, auto-create PO on stock below threshold.'],
                    ['key' => 'inventory-multi-location', 'name' => 'Multi-location Warehouses', 'description' => 'Multiple warehouse/location support, inter-location transfers, location-level reporting.'],
                    ['key' => 'inventory-barcode',        'name' => 'Barcode & QR Scanning',     'description' => 'Mobile barcode/QR scanning for stock movements, receiving, and stocktakes.'],
                    ['key' => 'inventory-batch-serial',   'name' => 'Batch & Serial Numbers',    'description' => 'Batch and serial number management, FIFO/LIFO/FEFO costing, full traceability.'],
                    ['key' => 'inventory-stocktake',      'name' => 'Stocktake & Cycle Count',   'description' => 'Full stocktake and rolling cycle count workflows, variance reporting, write-off/correction.'],
                    ['key' => 'inventory-returns',        'name' => 'Returns & RMA',              'description' => 'Return merchandise authorisation, receipt back to stock or write-off, linked to orders.'],
                ],
            ],
            [
                'key'         => 'operations-purchasing',
                'name'        => 'Purchasing & Procurement',
                'description' => 'Purchase order builder, supplier approval lists, goods receipt notes, 3-way matching, supplier portal.',
                'domain'      => 'operations',
                'panel_id'    => 'operations',
                'icon'        => 'heroicon-o-shopping-cart',
                'color'       => '#EA580C',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'operations-asset-management',
                'name'        => 'Asset Management',
                'description' => 'Track every physical asset. Assignment, QR labels, lifecycle stages, check-out/check-in, disposal recording.',
                'domain'      => 'operations',
                'panel_id'    => 'operations',
                'icon'        => 'heroicon-o-cube',
                'color'       => '#EA580C',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'operations-equipment-maintenance',
                'name'        => 'Equipment Maintenance (CMMS)',
                'description' => 'Preventive maintenance schedules, reactive work orders, fault reporting, parts tracking, downtime log.',
                'domain'      => 'operations',
                'panel_id'    => 'operations',
                'icon'        => 'heroicon-o-wrench-screwdriver',
                'color'       => '#EA580C',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'operations-field-service',
                'name'        => 'Field Service Management',
                'description' => 'Job dispatch, live map, route optimisation, mobile job app, digital sign-off, parts used from inventory.',
                'domain'      => 'operations',
                'panel_id'    => 'operations',
                'icon'        => 'heroicon-o-map-pin',
                'color'       => '#EA580C',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'operations-supply-chain',
                'name'        => 'Supply Chain Visibility',
                'description' => 'Order tracking from supplier to customer, supplier scorecards, lead time tracking, landed cost calculation.',
                'domain'      => 'operations',
                'panel_id'    => 'operations',
                'icon'        => 'heroicon-o-truck',
                'color'       => '#EA580C',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'operations-pos',
                'name'        => 'Point of Sale (POS)',
                'description' => 'Tablet/web POS for retail and hospitality. Real-time inventory sync, card/cash payments, Z-reports.',
                'domain'      => 'operations',
                'panel_id'    => 'operations',
                'icon'        => 'heroicon-o-device-tablet',
                'color'       => '#EA580C',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'operations-quality-control',
                'name'        => 'Quality Control & Inspections',
                'description' => 'Digital inspection checklists, pass/fail scoring, photo evidence, non-conformance reports, corrective actions.',
                'domain'      => 'operations',
                'panel_id'    => 'operations',
                'icon'        => 'heroicon-o-clipboard-document-check',
                'color'       => '#EA580C',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'operations-hse',
                'name'        => 'Health, Safety & Environment',
                'description' => 'Incident reporting, risk assessments, COSHH register, toolbox talks, RIDDOR reports, near-miss reporting.',
                'domain'      => 'operations',
                'panel_id'    => 'operations',
                'icon'        => 'heroicon-o-shield-exclamation',
                'color'       => '#EA580C',
                'is_core'     => false,
                'is_available'=> true,
            ],

            // ──────────────────────────────────────────────────────────
            // DOMAIN 7 — Analytics, BI & Reporting
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'analytics-dashboards',
                'name'        => 'Custom Dashboards',
                'description' => 'Drag-and-drop widget builder, data from any active module, role-based views, auto-refresh, share/embed.',
                'domain'      => 'analytics',
                'panel_id'    => 'analytics',
                'icon'        => 'heroicon-o-squares-2x2',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'analytics-report-builder',
                'name'        => 'Report Builder',
                'description' => 'Self-serve report builder, no SQL needed. Filter, group, sort, pivot, schedule, cross-module joins.',
                'domain'      => 'analytics',
                'panel_id'    => 'analytics',
                'icon'        => 'heroicon-o-table-cells',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'analytics-kpi-goals',
                'name'        => 'KPI & Goal Tracking',
                'description' => 'Define KPIs, cascade to departments and individuals, traffic-light status, trend charts, threshold alerts.',
                'domain'      => 'analytics',
                'panel_id'    => 'analytics',
                'icon'        => 'heroicon-o-flag',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'analytics-data-warehouse',
                'name'        => 'Data Warehouse & Export',
                'description' => 'BigQuery sync, Snowflake connector, S3/Azure Blob export, scheduled ETL jobs, data retention policies.',
                'domain'      => 'analytics',
                'panel_id'    => 'analytics',
                'icon'        => 'heroicon-o-server-stack',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'analytics-audit-log',
                'name'        => 'Audit Log & Activity Trail',
                'description' => 'Immutable log of every action. Who changed what, when, from which IP. Before/after values, compliance export.',
                'domain'      => 'analytics',
                'panel_id'    => 'analytics',
                'icon'        => 'heroicon-o-document-magnifying-glass',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'analytics-team-velocity',
                'name'        => 'Team Velocity & Operations Metrics',
                'description' => 'Cycle time, throughput charts, bottleneck detection, predictive delivery estimates, burnout signals.',
                'domain'      => 'analytics',
                'panel_id'    => 'analytics',
                'icon'        => 'heroicon-o-bolt',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],

            // ──────────────────────────────────────────────────────────
            // DOMAIN 8 — IT & Security Management
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'it-asset-management',
                'name'        => 'IT Asset Management (ITAM)',
                'description' => 'Hardware and software lifecycle tracking, licence compliance, renewal alerts, warranty, cost per asset.',
                'domain'      => 'it',
                'panel_id'    => 'it',
                'icon'        => 'heroicon-o-computer-desktop',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'it-helpdesk',
                'name'        => 'Internal IT Helpdesk',
                'description' => 'Employee IT issue portal, hardware fault reporting, software and access requests, SLA tracking.',
                'domain'      => 'it',
                'panel_id'    => 'it',
                'icon'        => 'heroicon-o-wrench',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'it-saas-spend',
                'name'        => 'SaaS Spend Management',
                'description' => 'SaaS discovery (incl. shadow IT), spend tracking, licence optimisation, renewal calendar, duplicate alerts.',
                'domain'      => 'it',
                'panel_id'    => 'it',
                'icon'        => 'heroicon-o-banknotes',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'it-access-audit',
                'name'        => 'Access & Permissions Audit',
                'description' => 'Cross-system access map, overprovision alerts, periodic access review cycles, auto-revoke on offboarding.',
                'domain'      => 'it',
                'panel_id'    => 'it',
                'icon'        => 'heroicon-o-key',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'it-security-compliance',
                'name'        => 'Security & Compliance',
                'description' => 'GDPR/ISO 27001/SOC 2 tooling, data processing register, DPIA templates, breach reporting, auditor evidence.',
                'domain'      => 'it',
                'panel_id'    => 'it',
                'icon'        => 'heroicon-o-lock-closed',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'it-uptime-monitoring',
                'name'        => 'Uptime & Status Monitoring',
                'description' => 'Monitor internal/client-facing services, public status page, incident management, alert rules, postmortem templates.',
                'domain'      => 'it',
                'panel_id'    => 'it',
                'icon'        => 'heroicon-o-signal',
                'color'       => '#0891B2',
                'is_core'     => false,
                'is_available'=> true,
            ],

            // ──────────────────────────────────────────────────────────
            // DOMAIN 9 — Legal & Compliance
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'legal-contract-management',
                'name'        => 'Contract Management (CLM)',
                'description' => 'Full contract lifecycle: template library, redlining, approval chains, e-signature, auto-renewal alerts.',
                'domain'      => 'legal',
                'panel_id'    => 'legal',
                'icon'        => 'heroicon-o-document-text',
                'color'       => '#B45309',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'legal-policy-management',
                'name'        => 'Policy Management',
                'description' => 'Company policy publishing, version control, employee acknowledgement tracking, scheduled review reminders.',
                'domain'      => 'legal',
                'panel_id'    => 'legal',
                'icon'        => 'heroicon-o-clipboard-document',
                'color'       => '#B45309',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'legal-risk-register',
                'name'        => 'Risk Register',
                'description' => 'Risk identification, likelihood × impact matrix, ownership assignment, mitigation tracking, board-level export.',
                'domain'      => 'legal',
                'panel_id'    => 'legal',
                'icon'        => 'heroicon-o-exclamation-triangle',
                'color'       => '#B45309',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'legal-data-privacy',
                'name'        => 'Data Privacy (GDPR / CCPA)',
                'description' => 'DSR handling, right to erasure automation, consent management, Article 30 register, cookie banner.',
                'domain'      => 'legal',
                'panel_id'    => 'legal',
                'icon'        => 'heroicon-o-shield-check',
                'color'       => '#B45309',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'legal-insurance-licences',
                'name'        => 'Insurance & Licence Tracking',
                'description' => 'Business insurance register, regulatory licence register, expiry alerts, document vault, renewal reminders.',
                'domain'      => 'legal',
                'panel_id'    => 'legal',
                'icon'        => 'heroicon-o-identification',
                'color'       => '#B45309',
                'is_core'     => false,
                'is_available'=> true,
            ],

            // ──────────────────────────────────────────────────────────
            // DOMAIN 10 — E-commerce & Sales Channels
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'ecommerce-product-catalogue',
                'name'        => 'Product Catalogue',
                'description' => 'Centralised product database, variants, pricing tiers, tax codes, image gallery, bulk import/export.',
                'domain'      => 'ecommerce',
                'panel_id'    => 'ecommerce',
                'icon'        => 'heroicon-o-tag',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'ecommerce-order-management',
                'name'        => 'Order Management',
                'description' => 'Multi-channel order import, order status workflow, fulfillment tracking, returns, packing slips, 3PL integration.',
                'domain'      => 'ecommerce',
                'panel_id'    => 'ecommerce',
                'icon'        => 'heroicon-o-clipboard-document-list',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'orders-multi-channel',  'name' => 'Multi-channel Import',     'description' => 'Import orders from website, POS, and marketplaces into a single order queue.'],
                    ['key' => 'orders-fulfillment',    'name' => 'Fulfillment & Shipping',   'description' => 'Fulfillment tracking, partial/split shipping, packing slips, shipping label printing.'],
                    ['key' => 'orders-returns-refunds','name' => 'Returns & Refunds',        'description' => 'Return processing, refund to payment method, linked to Finance module.'],
                    ['key' => 'orders-dropshipping',   'name' => 'Dropshipping & 3PL',       'description' => 'Dropship supplier routing, 3PL integration (ShipBob, ShipStation), customs documentation.'],
                ],
            ],
            [
                'key'         => 'ecommerce-storefront',
                'name'        => 'Storefront & Checkout',
                'description' => 'Customisable branded storefront, product pages, cart, checkout, Stripe/PayPal/Klarna/Apple Pay, discount codes.',
                'domain'      => 'ecommerce',
                'panel_id'    => 'ecommerce',
                'icon'        => 'heroicon-o-shopping-bag',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'ecommerce-marketplace-sync',
                'name'        => 'Marketplace Channel Sync',
                'description' => 'Sync listings and orders from Amazon, eBay, Etsy. Centralised stock control, listing management.',
                'domain'      => 'ecommerce',
                'panel_id'    => 'ecommerce',
                'icon'        => 'heroicon-o-arrows-right-left',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'ecommerce-subscription-products',
                'name'        => 'Subscription Products',
                'description' => 'Recurring billing cadences, customer pause/cancel flows, dunning, box and bundle builder.',
                'domain'      => 'ecommerce',
                'panel_id'    => 'ecommerce',
                'icon'        => 'heroicon-o-arrow-path',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'ecommerce-digital-products',
                'name'        => 'Digital Products & Downloads',
                'description' => 'File delivery automation post-purchase, download limits, licence key generation, access expiry.',
                'domain'      => 'ecommerce',
                'panel_id'    => 'ecommerce',
                'icon'        => 'heroicon-o-arrow-down-tray',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],

            // ──────────────────────────────────────────────────────────
            // DOMAIN 11 — Communications & Internal Comms
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'comms-messaging',
                'name'        => 'Internal Messaging & Chat',
                'description' => 'Real-time channels, DMs, threads, file sharing, task linking, search history, reactions. Slack alternative.',
                'domain'      => 'communications',
                'panel_id'    => 'communications',
                'icon'        => 'heroicon-o-chat-bubble-left-right',
                'color'       => '#0F766E',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'comms-announcements',
                'name'        => 'Company Announcements',
                'description' => 'Internal broadcast tool, targeted audience, read receipt tracking, acknowledgement required, announcement archive.',
                'domain'      => 'communications',
                'panel_id'    => 'communications',
                'icon'        => 'heroicon-o-megaphone',
                'color'       => '#0F766E',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'comms-meeting-video',
                'name'        => 'Meeting & Video Integration',
                'description' => 'Schedule and join Google Meet/Zoom from within the platform. Auto-create meeting notes, action items.',
                'domain'      => 'communications',
                'panel_id'    => 'communications',
                'icon'        => 'heroicon-o-video-camera',
                'color'       => '#0F766E',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'comms-intranet',
                'name'        => 'Company Intranet & Noticeboard',
                'description' => 'Organisation homepage, company news feed, quick links, org chart, events calendar, role-based widgets.',
                'domain'      => 'communications',
                'panel_id'    => 'communications',
                'icon'        => 'heroicon-o-home',
                'color'       => '#0F766E',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'comms-booking-scheduling',
                'name'        => 'Booking & Appointment Scheduling',
                'description' => 'Booking page builder, availability rules, calendar sync, group bookings, round-robin, confirmation emails/SMS.',
                'domain'      => 'communications',
                'panel_id'    => 'communications',
                'icon'        => 'heroicon-o-calendar',
                'color'       => '#0F766E',
                'is_core'     => false,
                'is_available'=> true,
            ],

            // ──────────────────────────────────────────────────────────
            // DOMAIN 12 — Learning & Development (LMS)
            // ──────────────────────────────────────────────────────────
            [
                'key'         => 'learning-lms-courses',
                'name'        => 'Course Builder & LMS',
                'description' => 'Course builder (video/doc/quiz), assignment by role, completion tracking, certificates, SCORM import, AI quiz generation.',
                'domain'      => 'learning',
                'panel_id'    => 'learning',
                'icon'        => 'heroicon-o-academic-cap',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
                'sub_modules' => [
                    ['key' => 'lms-course-builder',     'name' => 'Course Builder',           'description' => 'Block-based course builder: video, documents, quizzes, embeds.'],
                    ['key' => 'lms-assignment',         'name' => 'Course Assignment',         'description' => 'Assign courses by role or department, auto-assign on hire or role change.'],
                    ['key' => 'lms-tracking',           'name' => 'Completion Tracking',       'description' => 'Progress percentage, completion status, time spent, pass/fail thresholds.'],
                    ['key' => 'lms-certificates',       'name' => 'Certificate Generation',    'description' => 'Branded PDF certificates on completion, expiry tracking, renewal triggers.'],
                    ['key' => 'lms-scorm',              'name' => 'SCORM Import',              'description' => 'Import existing SCORM 1.2 and 2004 e-learning content packages.'],
                    ['key' => 'lms-gamification',       'name' => 'Gamification & Leaderboards','description' => 'Points, badges, leaderboards, streaks to drive course completion.'],
                ],
            ],
            [
                'key'         => 'learning-skills-matrix',
                'name'        => 'Skills Matrix & Gap Analysis',
                'description' => 'Skills library, role skill requirements, employee self-assessment, gap analysis dashboard, training recommendations.',
                'domain'      => 'learning',
                'panel_id'    => 'learning',
                'icon'        => 'heroicon-o-puzzle-piece',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'learning-succession-planning',
                'name'        => 'Succession Planning',
                'description' => '9-box talent grid, succession readiness scoring, key role risk flags, development path builder.',
                'domain'      => 'learning',
                'panel_id'    => 'learning',
                'icon'        => 'heroicon-o-arrows-up-down',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'learning-mentoring',
                'name'        => 'Mentoring & Coaching',
                'description' => 'Mentor matching, session scheduling, progress tracking, programme management, coaching network directory.',
                'domain'      => 'learning',
                'panel_id'    => 'learning',
                'icon'        => 'heroicon-o-users',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
            [
                'key'         => 'learning-external-training',
                'name'        => 'External Training Requests',
                'description' => 'Employee training request form, manager approval, L&D budget tracking, post-training knowledge sharing.',
                'domain'      => 'learning',
                'panel_id'    => 'learning',
                'icon'        => 'heroicon-o-arrow-top-right-on-square',
                'color'       => '#7C3AED',
                'is_core'     => false,
                'is_available'=> true,
            ],
        ];
    }
}
